travis:
  secure:
    BINSTAR_TOKEN: CbyhhWV9pPUOxRkqapa7jN6nk2gHTTRZL10Gu1RvMOXDDfPy6JldAlKNigKs6zspa3pKgbTZbgev7WXfi2GxxgZdXDujgzSk7qeUfWBmHgHeayDIY1PeiM37rIIeR8w2DuVu7qlYkX4prhplE8UvZ8FEgE1cwmFu9FNECLiTly/jhigiTfZsERcGCdLsxBwXNWGx63Ax4R1JfEuwYza2sEzVztpuiliJ/v6X7knYjqVWHT4oT6eSlsuksbXxKPKRsnwrCKGe+1+W3PV+iuymfVRxLsN0E78SCw/iW+Pkyaewmh1NxB4sYDduISSdc/RIz371dCzbsgYXkw6RtOrKH15o5uFVhsYiwVOsu7Oi0yxGpfcWq34KaS1x3vXPxL3bzN7bVwuN/0dVTOXYKQ7z0vVoaP3oVsJsL4zthXal60BMNKkFDdUsXlvpjYQ0+8swNNvU3Bd3igxbEoQc1i7uBmPu1vfLao92mWWJhEHTYwzdEYqwKMSQ2GJX6gaXPVLhrtmA59V6Jm1MoUPF3TzsTK8F3UHu/c5puRF+qLC+rIYN4pdJcQP5/Tzqq/h5lraFQdUB0TGkbf+77OQc8TNQ25Q+uWQoBFDftj7o/1FMFh1y7FH0W34zmQExB5TWZXXOOWIxoPKJuWzMb7ivT8fAktVHG6gX2SCalFBKd5KEi4U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
